export default {
  USER_AUTHORIZATION_ERROR: 'USER_AUTHORIZATION_ERROR',

  USER_SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',

  USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',

  USER_AUTHENTICATION_REQUEST: 'USER_AUTHENTICATION_REQUEST',
  USER_AUTHENTICATION_SUCCESS: 'USER_AUTHENTICATION_SUCCESS',

  USER_LOG_OUT: 'USER_LOG_OUT',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',

  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',

  PROFILE_UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
};
