export default {
  USER_SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
  USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',
  USER_AUTHENTICATION_SUCCESS: 'USER_AUTHENTICATION_SUCCESS',
  USER_AUTHENTICATION_ERROR: 'USER_AUTHENTICATION_ERROR',
  USER_LOG_OUT: 'USER_LOG_OUT',

  USERS_LIST_REQUEST: 'USERS_LIST_REQUEST',
  USERS_LIST_SUCCESS: 'USERS_LIST_SUCCESS',
  USERS_LIST_FAILURE: 'USERS_LIST_FAILURE',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',
};
