export default {
  USER_SIGN_UP_REQUEST: 'USER_SIGN_UP_REQUEST',
  USER_SIGN_IN_REQUEST: 'USER_SIGN_IN_REQUEST',
  USER_AUTHENTICATION_SUCCESS: 'USER_AUTHENTICATION_SUCCESS',
  USER_AUTHENTICATION_ERROR: 'USER_AUTHENTICATION_ERROR',
  USER_LOG_OUT: 'USER_LOG_OUT',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
};
