export default {
  BOOK_CREATE_REQUEST: 'BOOK_CREATE_REQUEST',
  BOOK_CREATE_SUCCESS: 'BOOK_CREATE_SUCCESS',

  BOOKS_GET_REQUEST: 'BOOKS_GET_REQUEST',
  BOOKS_GET_SUCCESS: 'BOOKS_GET_SUCCESS',

  BOOK_UPDATE_REQUEST: 'BOOK_UPDATE_REQUEST',
  BOOK_UPDATE_SUCCESS: 'BOOK_UPDATE_SUCCESS',

  BOOK_DELETE_REQUEST: 'BOOK_DELETE_REQUEST',
  BOOK_DELETE_SUCCESS: 'BOOK_DELETE_SUCCESS',

  BOOK_REQUEST_FAILURE: 'BOOK_REQUEST_FAILURE',
};
