export default {
  CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
  CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',

  CATEGORIES_GET_REQUEST: 'CATEGORIES_GET_REQUEST',
  CATEGORIES_GET_SUCCESS: 'CATEGORIES_GET_SUCCESS',

  CATEGORY_UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUEST',
  CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',

  CATEGORY_DELETE_REQUEST: 'CATEGORY_DELETE_REQUEST',
  CATEGORY_DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',

  CATEGORY_REQUEST_FAILURE: 'CATEGORY_REQUEST_FAILURE',
};
