export default {
  CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
  CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
  CATEGORY_CREATE_FAILURE: 'CATEGORY_CREATE_FAILURE',

  CATEGORIES_GET_REQUEST: 'CATEGORIES_GET_REQUEST',
  CATEGORIES_GET_SUCCESS: 'CATEGORIES_GET_SUCCESS',
  CATEGORIES_GET_FAILURE: 'CATEGORIES_GET_FAILURE',

  CATEGORY_UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUEST',
  CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
  CATEGORY_UPDATE_FAILURE: 'CATEGORY_UPDATE_FAILURE',

  CATEGORY_DELETE_REQUEST: 'CATEGORY_DELETE_REQUEST',
  CATEGORY_DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
  CATEGORY_DELETE_FAILURE: 'CATEGORY_DELETE_FAILURE',

};
