export default {
  AUTHOR_CREATE_REQUEST: 'AUTHOR_CREATE_REQUEST',
  AUTHOR_CREATE_SUCCESS: 'AUTHOR_CREATE_SUCCESS',

  AUTHORS_GET_REQUEST: 'AUTHORS_GET_REQUEST',
  AUTHORS_GET_SUCCESS: 'AUTHORS_GET_SUCCESS',

  AUTHOR_UPDATE_REQUEST: 'AUTHOR_UPDATE_REQUEST',
  AUTHOR_UPDATE_SUCCESS: 'AUTHOR_UPDATE_SUCCESS',

  AUTHOR_DELETE_REQUEST: 'AUTHOR_DELETE_REQUEST',
  AUTHOR_DELETE_SUCCESS: 'AUTHOR_DELETE_SUCCESS',

  AUTHOR_REQUEST_FAILURE: 'AUTHOR_REQUEST_FAILURE',
};
