export default {

  USERS_LIST_REQUEST: 'USERS_LIST_REQUEST',
  USERS_LIST_SUCCESS: 'USERS_LIST_SUCCESS',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',

  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',

  USER_REQUEST_FAILURE: 'USER_REQUEST_FAILURE',
};
